// <auto-generated />
using System;
using AydosRobotics_WEB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AydosRobotics_WEB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250912175226_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AydosRobotics_WEB.Models.DriveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RobotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique()
                        .HasFilter("[RobotId] IS NOT NULL");

                    b.ToTable("DriveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tank Drive"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mecanum Drive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Swerve Drive"
                        },
                        new
                        {
                            Id = 4,
                            Name = "H Drive"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Octanum/Butterfly Drive"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kiwi Drive (Omni Wheels)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Holonomic Drive (Omni Wheel X-Drive)"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Treads"
                        });
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NEO",
                            Type = "Brushless",
                            Vendor = "REV Robotics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NEO 550",
                            Type = "Brushless",
                            Vendor = "REV Robotics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Falcon 500",
                            Type = "Brushless",
                            Vendor = "Falcon FX"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CIM",
                            Type = "Brushed",
                            Vendor = "AndyMark"
                        },
                        new
                        {
                            Id = 5,
                            Name = "mini CIM",
                            Type = "Brushed",
                            Vendor = "AndyMark"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BAG",
                            Type = "Brushed",
                            Vendor = "AndyNark"
                        },
                        new
                        {
                            Id = 7,
                            Name = "775pro",
                            Type = "Brushed",
                            Vendor = "VEX"
                        },
                        new
                        {
                            Id = 8,
                            Name = "RedLine",
                            Type = "Brushed",
                            Vendor = "AndyNark"
                        });
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.MotorDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MotorDrivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Talon SR",
                            Type = "PWM",
                            Vendor = "CTRE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Talon SRX",
                            Type = "CAN",
                            Vendor = "CTRE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Victor SP",
                            Type = "PWM",
                            Vendor = "VEX Robotics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Victor SPX",
                            Type = "CAN",
                            Vendor = "VEX Robotics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SPARK",
                            Type = "PWM",
                            Vendor = "REV Robotics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SPARK MAX",
                            Type = "CAN",
                            Vendor = "REV Robotics"
                        });
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutonomousDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Regional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<bool>("Taxi")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.RobotMotor", b =>
                {
                    b.Property<int>("RobotId")
                        .HasColumnType("int");

                    b.Property<int>("MotorId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RobotId", "MotorId");

                    b.HasIndex("MotorId");

                    b.ToTable("RobotMotors");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.RobotMotorDriver", b =>
                {
                    b.Property<int>("RobotId")
                        .HasColumnType("int");

                    b.Property<int>("MotorDriverId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RobotId", "MotorDriverId");

                    b.HasIndex("MotorDriverId");

                    b.ToTable("RobotMotorDrivers");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mentor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeamPitNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.DriveType", b =>
                {
                    b.HasOne("AydosRobotics_WEB.Models.Robot", "Robot")
                        .WithOne("DriveType")
                        .HasForeignKey("AydosRobotics_WEB.Models.DriveType", "RobotId");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Robot", b =>
                {
                    b.HasOne("AydosRobotics_WEB.Models.Team", "Team")
                        .WithMany("Robot")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.RobotMotor", b =>
                {
                    b.HasOne("AydosRobotics_WEB.Models.Motor", "Motor")
                        .WithMany("RobotMotors")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AydosRobotics_WEB.Models.Robot", "Robot")
                        .WithMany("RobotMotors")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.RobotMotorDriver", b =>
                {
                    b.HasOne("AydosRobotics_WEB.Models.MotorDriver", "MotorDriver")
                        .WithMany("RobotMotorDrivers")
                        .HasForeignKey("MotorDriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AydosRobotics_WEB.Models.Robot", "Robot")
                        .WithMany("RobotMotorDrivers")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotorDriver");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Motor", b =>
                {
                    b.Navigation("RobotMotors");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.MotorDriver", b =>
                {
                    b.Navigation("RobotMotorDrivers");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Robot", b =>
                {
                    b.Navigation("DriveType")
                        .IsRequired();

                    b.Navigation("RobotMotorDrivers");

                    b.Navigation("RobotMotors");
                });

            modelBuilder.Entity("AydosRobotics_WEB.Models.Team", b =>
                {
                    b.Navigation("Robot");
                });
#pragma warning restore 612, 618
        }
    }
}
